<?php
/**
 * Since we are using a service locator pattern this is where the services are loaded.
 * This of course can be overridden to mock services as need
 */

return [
	'auth'=>'\projectorangebox\orange\library\Auth',
	'cache'=>'\projectorangebox\orange\library\Cache',
	'errors'=>'\projectorangebox\orange\library\Errors',
	'event'=>'\projectorangebox\orange\library\Event',
	'page'=>'\projectorangebox\orange\library\Page',
	'validate'=>'\projectorangebox\orange\library\Validate',
	'wallet'=>'\projectorangebox\orange\library\Wallet',
	'session'=>'\projectorangebox\orange\library\Session',

	'config'=>'\projectorangebox\orange\library\Config',
	'log'=>'\projectorangebox\orange\library\Log',
	'router'=>'\projectorangebox\orange\library\Router',
	'output'=>'\projectorangebox\orange\library\Output',
	'input'=>'\projectorangebox\orange\library\Input',

	'o_user_model'=>'\projectorangebox\orange\model\O_user_model',

	'example_model'=>'\projectorangebox\theme\model\Example_model',

	'cache_drivers'=> [
		'apc' => 'CI_Cache_apc',
		'dummy' => 'CI_Cache_dummy',
		'file' => 'CI_Cache_file',
		'memcached' => 'CI_Cache_memcached',
		'redis' => 'CI_Cache_redis',
		'wincache' => 'CI_Cache_wincache',
		'export' => '\projectorangebox\orange\library\cache\Export',
		'request' => '\projectorangebox\orange\library\cache\Request',
	],

	'filter_float' => '\projectorangebox\orange\library\filters\Filter_float',
	'filter_filename' => '\projectorangebox\orange\library\filters\Filter_filename',
	'filter_length' => '\projectorangebox\orange\library\filters\Filter_length',
	'filter_convert_date' => '\projectorangebox\orange\library\filters\Filter_convert_date',
	'filter_int' => '\projectorangebox\orange\library\filters\Filter_int',
	'filter_human' => '\projectorangebox\orange\library\filters\Filter_human',
	'filter_textarea' => '\projectorangebox\orange\library\filters\Filter_textarea',
	'filter_str' => '\projectorangebox\orange\library\filters\Filter_str',
	'filter_visible' => '\projectorangebox\orange\library\filters\Filter_visible',
	'filter_slug' => '\projectorangebox\orange\library\filters\Filter_slug',
	'filter_input' => '\projectorangebox\orange\library\filters\Filter_input',

	'pear_include' => '\projectorangebox\orange\library\pear_plugins\Pear_include',
	'pear_section' => '\projectorangebox\orange\library\pear_plugins\Pear_section',
	'pear_plugins' => '\projectorangebox\orange\library\pear_plugins\Pear_plugins',
	'pear_end' => '\projectorangebox\orange\library\pear_plugins\Pear_end',
	'pear_extends' => '\projectorangebox\orange\library\pear_plugins\Pear_extends',
	'pear_page' => '\projectorangebox\orange\library\pear_plugins\Pear_page',
	'pear_parent' => '\projectorangebox\orange\library\pear_plugins\Pear_parent',
	'pear_goback_button' => '\projectorangebox\theme\library\pear_plugins\Pear_goback_button',
	'pear_date_picker' => '\projectorangebox\theme\library\pear_plugins\Pear_date_picker',
	'pear_date' => '\projectorangebox\theme\library\pear_plugins\Pear_date',
	'pear_bootbox' => '\projectorangebox\theme\library\pear_plugins\Pear_bootbox',
	'pear_role_permission' => '\projectorangebox\theme\library\pear_plugins\Pear_role_permission',
	'pear_combobox' => '\projectorangebox\theme\library\pear_plugins\Pear_combobox',
	'pear_sortable' => '\projectorangebox\theme\library\pear_plugins\Pear_sortable',
	'pear_header_button' => '\projectorangebox\theme\library\pear_plugins\Pear_header_button',
	'pear_bootstrap_wysiwyg' => '\projectorangebox\theme\library\pear_plugins\Pear_bootstrap_wysiwyg',
	'pear_table_sticky_header' => '\projectorangebox\theme\library\pear_plugins\Pear_table_sticky_header',
	'pear_field_range' => '\projectorangebox\theme\library\pear_plugins\Pear_field_range',
	'pear_color_value' => '\projectorangebox\theme\library\pear_plugins\Pear_color_value',
	'pear_select3' => '\projectorangebox\theme\library\pear_plugins\Pear_select3',
	'pear_bootstrapnav' => '\projectorangebox\theme\library\pear_plugins\Pear_bootstrapNav',
	'pear_color_picker' => '\projectorangebox\theme\library\pear_plugins\Pear_color_picker',
	'pear_html_tag' => '\projectorangebox\theme\library\pear_plugins\Pear_html_tag',
	'pear_echo' => '\projectorangebox\orange\library\pear_plugins\Pear_echo',
	'pear_nestable' => '\projectorangebox\theme\library\pear_plugins\Pear_nestable',
	'pear_table_sort' => '\projectorangebox\theme\library\pear_plugins\Pear_table_sort',
	'pear_confirm_dialog' => '\projectorangebox\theme\library\pear_plugins\Pear_confirm_dialog',
	'pear_field_label' => '\projectorangebox\theme\library\pear_plugins\Pear_field_label',
	'pear_color_block' => '\projectorangebox\theme\library\pear_plugins\Pear_color_block',
	'pear_fa_dropdown' => '\projectorangebox\theme\library\pear_plugins\Pear_fa_dropdown',
	'pear_back_to_top' => '\projectorangebox\theme\library\pear_plugins\Pear_back_to_top',
	'pear_html_list' => '\projectorangebox\theme\library\pear_plugins\Pear_html_list',
	'pear_flash_msg' => '\projectorangebox\theme\library\pear_plugins\Pear_flash_msg',
	'pear_fa_icon' => '\projectorangebox\theme\library\pear_plugins\Pear_fa_icon',
	'pear_asset_route' => '\projectorangebox\theme\library\pear_plugins\Pear_asset_route',
	'pear_new_button' => '\projectorangebox\theme\library\pear_plugins\Pear_new_button',
	'pear_menu_li' => '\projectorangebox\theme\library\pear_plugins\Pear_menu_li',
	'pear_color_fa_icon' => '\projectorangebox\theme\library\pear_plugins\Pear_color_fa_icon',
	'pear_input_mask' => '\projectorangebox\theme\library\pear_plugins\Pear_input_mask',
	'pear_money' => '\projectorangebox\theme\library\pear_plugins\Pear_money',
	'pear_checker' => '\projectorangebox\theme\library\pear_plugins\Pear_checker',
	'pear_role_dropdown' => '\projectorangebox\theme\library\pear_plugins\Pear_role_dropdown',
	'pear_textarea' => '\projectorangebox\theme\library\pear_plugins\Pear_textarea',
	'pear_field_human' => '\projectorangebox\theme\library\pear_plugins\Pear_field_human',
	'pear_title' => '\projectorangebox\theme\library\pear_plugins\Pear_title',
	'pear_tab_id' => '\projectorangebox\theme\library\pear_plugins\Pear_tab_id',
	'pear_keymaster' => '\projectorangebox\theme\library\pear_plugins\Pear_keymaster',
	'pear_sprintf' => '\projectorangebox\theme\library\pear_plugins\Pear_sprintf',
	'pear_delete_button' => '\projectorangebox\theme\library\pear_plugins\Pear_delete_button',
	'pear_e' => '\projectorangebox\theme\library\pear_plugins\Pear_e',
	'pear_user' => '\projectorangebox\theme\library\pear_plugins\Pear_user',
	'pear_table_remember_position' => '\projectorangebox\theme\library\pear_plugins\Pear_table_remember_position',
	'pear_datalist' => '\projectorangebox\theme\library\pear_plugins\Pear_datalist',
	'pear_bound_table_search_field' => '\projectorangebox\theme\library\pear_plugins\Pear_bound_table_search_field',
	'pear_date_time_picker' => '\projectorangebox\theme\library\pear_plugins\Pear_date_time_picker',
	'pear_summernote' => '\projectorangebox\theme\library\pear_plugins\Pear_summernote',
	'pear_form_help' => '\projectorangebox\theme\library\pear_plugins\Pear_form_help',
	'pear_index_row_button' => '\projectorangebox\theme\library\pear_plugins\Pear_index_row_button',
	'pear_example_close' => '\projectorangebox\theme\library\pear_plugins\Pear_example_close',
	'pear_form_static' => '\projectorangebox\theme\library\pear_plugins\Pear_form_static',
	'pear_edit_button' => '\projectorangebox\theme\library\pear_plugins\Pear_edit_button',
	'pear_time_picker' => '\projectorangebox\theme\library\pear_plugins\Pear_time_picker',
	'pear_table_search_field' => '\projectorangebox\theme\library\pear_plugins\Pear_table_search_field',
	'pear_asset_include' => '\projectorangebox\theme\library\pear_plugins\Pear_asset_include',
	'pear_locked_field' => '\projectorangebox\theme\library\pear_plugins\Pear_locked_field',
	'pear_example_open' => '\projectorangebox\theme\library\pear_plugins\Pear_example_open',
	'pear_wrap' => '\projectorangebox\theme\library\pear_plugins\Pear_wrap',
	'pear_uri' => '\projectorangebox\theme\library\pear_plugins\Pear_uri',
	'pear_asset' => '\projectorangebox\theme\library\pear_plugins\Pear_asset',
	'pear_notify' => '\projectorangebox\theme\library\pear_plugins\Pear_notify',
	'pear_tab_prepare' => '\projectorangebox\theme\library\pear_plugins\Pear_tab_prepare',
	'pear_fa_enum_icon' => '\projectorangebox\theme\library\pear_plugins\Pear_fa_enum_icon',
	'pear_tabs' => '\projectorangebox\theme\library\pear_plugins\Pear_tabs',
	'pear_form_helpers' => '\projectorangebox\theme\library\pear_plugins\Pear_form_helpers',
	'pear_rest_form' => '\projectorangebox\theme\library\pear_plugins\Pear_rest_form',
	'pear_tab_title' => '\projectorangebox\theme\library\pear_plugins\Pear_tab_title',
	'pear_tab_save' => '\projectorangebox\theme\library\pear_plugins\Pear_tab_save',
	'pear_catalog_dropdown' => '\projectorangebox\theme\library\pear_plugins\Pear_catalog_dropdown',
	'pear_date_picker_main' => '\projectorangebox\theme\library\pear_plugins\Pear_date_picker_main',
	'pear_catalog_lookup' => '\projectorangebox\theme\library\pear_plugins\Pear_catalog_lookup',

	'validate_decimal' => '\projectorangebox\orange\library\validations\Validate_decimal',
	'validate_valid_emails' => '\projectorangebox\orange\library\validations\Validate_valid_emails',
	'validate_valid_ip' => '\projectorangebox\orange\library\validations\Validate_valid_ip',
	'validate_max_length' => '\projectorangebox\orange\library\validations\Validate_max_length',
	'validate_matches' => '\projectorangebox\orange\library\validations\Validate_matches',
	'validate_valid_url' => '\projectorangebox\orange\library\validations\Validate_valid_url',
	'validate_integer' => '\projectorangebox\orange\library\validations\Validate_integer',
	'validate_greater_than_equal_to' => '\projectorangebox\orange\library\validations\Validate_greater_than_equal_to',
	'validate_alpha' => '\projectorangebox\orange\library\validations\Validate_alpha',
	'validate_is_unique' => '\projectorangebox\orange\library\validations\Validate_is_unique',
	'validate_regex_match' => '\projectorangebox\orange\library\validations\Validate_regex_match',
	'validate_valid_base64' => '\projectorangebox\orange\library\validations\Validate_valid_base64',
	'validate_alpha_dash' => '\projectorangebox\orange\library\validations\Validate_alpha_dash',
	'validate_alpha_numeric_spaces' => '\projectorangebox\orange\library\validations\Validate_alpha_numeric_spaces',
	'validate_alpha_numeric' => '\projectorangebox\orange\library\validations\Validate_alpha_numeric',
	'validate_exact_length' => '\projectorangebox\orange\library\validations\Validate_exact_length',
	'validate_alpha_space' => '\projectorangebox\orange\library\validations\Validate_alpha_space',
	'validate_less_than' => '\projectorangebox\orange\library\validations\Validate_less_than',
	'validate_in_list' => '\projectorangebox\orange\library\validations\Validate_in_list',
	'validate_greater_than' => '\projectorangebox\orange\library\validations\Validate_greater_than',
	'validate_is_natural' => '\projectorangebox\orange\library\validations\Validate_is_natural',
	'validate_differs' => '\projectorangebox\orange\library\validations\Validate_differs',
	'validate_valid_email' => '\projectorangebox\orange\library\validations\Validate_valid_email',
	'validate_has_errors' => '\projectorangebox\orange\library\validations\Validate_has_errors',
	'validate_is_natural_no_zero' => '\projectorangebox\orange\library\validations\Validate_is_natural_no_zero',
	'validate_min_length' => '\projectorangebox\orange\library\validations\Validate_min_length',
	'validate_numeric' => '\projectorangebox\orange\library\validations\Validate_numeric',
	'validate_required' => '\projectorangebox\orange\library\validations\Validate_required',
	'validate_less_than_equal_to' => '\projectorangebox\orange\library\validations\Validate_less_than_equal_to',

	'#form/test' => '/packages/projectorangebox/theme/views/form/test.php',
	'#_templates/orange_admin' => '/packages/projectorangebox/theme/views/_templates/orange_admin.php',
	'#_templates/access' => '/packages/projectorangebox/theme/views/_templates/access.php',
	'#_templates/nav' => '/packages/projectorangebox/theme/views/_templates/nav.php',
	'#_templates/footer' => '/packages/projectorangebox/theme/views/_templates/footer.php',
	'#_templates/blank' => '/packages/projectorangebox/theme/views/_templates/blank.php',
	'#_templates/header' => '/packages/projectorangebox/theme/views/_templates/header.php',
	'#_templates/orange_default' => '/packages/projectorangebox/theme/views/_templates/orange_default.php',
	'#cats' => '/packages/projectorangebox/theme/views/cats.php',
	'#form' => '/application/views/form.php',
	'#main/welcome' => '/application/views/welcome/index.php',
	'#welcome_message' => '/application/views/welcome_message.php',
	'#errors/html/error_db' => '/application/views/errors/html/error_db.php',
	'#errors/html/error_404' => '/application/views/errors/html/error_404.php',
	'#errors/html/error_php' => '/application/views/errors/html/error_php.php',
	'#errors/html/error_exception' => '/application/views/errors/html/error_exception.php',
	'#errors/html/error_general' => '/application/views/errors/html/error_general.php',
	'#errors/cli/error_db' => '/application/views/errors/cli/error_db.php',
	'#errors/cli/error_404' => '/application/views/errors/cli/error_404.php',
	'#errors/cli/error_php' => '/application/views/errors/cli/error_php.php',
	'#errors/cli/error_exception' => '/application/views/errors/cli/error_exception.php',
	'#errors/cli/error_general' => '/application/views/errors/cli/error_general.php',

];
