<?php
/**
 * Since we are using a service locator pattern this is where the services are loaded.
 * This of course can be overridden to mock services as need
 */

return [
	'auth'=>'\projectorangebox\orange\library\Auth',
	'cache'=>'\projectorangebox\orange\library\Cache',
	'errors'=>'\projectorangebox\orange\library\Errors',
	'event'=>'\projectorangebox\orange\library\Event',
	'page'=>'\projectorangebox\orange\library\Page',
	'validate'=>'\projectorangebox\orange\library\Validate',
	'wallet'=>'\projectorangebox\orange\library\Wallet',
	'session'=>'\projectorangebox\orange\library\Session',

	'config'=>'\projectorangebox\orange\library\Config',
	'log'=>'\projectorangebox\orange\library\Log',
	'router'=>'\projectorangebox\orange\library\Router',
	'output'=>'\projectorangebox\orange\library\Output',
	'input'=>'\projectorangebox\orange\library\Input',

	'o_user_model'=>'\projectorangebox\orange\model\O_user_model',

	'example_model'=>'\projectorangebox\theme\model\Example_model',

	'filter_float' => '\projectorangebox\orange\library\filters\Filter_float',
	'filter_filename' => '\projectorangebox\orange\library\filters\Filter_filename',
	'filter_length' => '\projectorangebox\orange\library\filters\Filter_length',
	'filter_convert_date' => '\projectorangebox\orange\library\filters\Filter_convert_date',
	'filter_int' => '\projectorangebox\orange\library\filters\Filter_int',
	'filter_human' => '\projectorangebox\orange\library\filters\Filter_human',
	'filter_textarea' => '\projectorangebox\orange\library\filters\Filter_textarea',
	'filter_str' => '\projectorangebox\orange\library\filters\Filter_str',
	'filter_visible' => '\projectorangebox\orange\library\filters\Filter_visible',
	'filter_slug' => '\projectorangebox\orange\library\filters\Filter_slug',
	'filter_input' => '\projectorangebox\orange\library\filters\Filter_input',

	'pear_include' => '\projectorangebox\orange\library\pear_plugins\Pear_include',
	'pear_section' => '\projectorangebox\orange\library\pear_plugins\Pear_section',
	'pear_echo' => '\projectorangebox\orange\library\pear_plugins\Pear_echo',
	'pear_plugins' => '\projectorangebox\orange\library\pear_plugins\Pear_plugins',
	'pear_end' => '\projectorangebox\orange\library\pear_plugins\Pear_end',
	'pear_wrap' => '\projectorangebox\orange\library\pear_plugins\Pear_wrap',
	'pear_extends' => '\projectorangebox\orange\library\pear_plugins\Pear_extends',
	'pear_page' => '\projectorangebox\orange\library\pear_plugins\Pear_page',
	'pear_parent' => '\projectorangebox\orange\library\pear_plugins\Pear_parent',
	'pear_title' => '\projectorangebox\theme\library\pear_plugins\Pear_title',
	'pear_asset_route' => '\projectorangebox\theme\library\pear_plugins\Pear_asset_route',

	'validate_decimal' => '\projectorangebox\orange\library\validations\Validate_decimal',
	'validate_valid_emails' => '\projectorangebox\orange\library\validations\Validate_valid_emails',
	'validate_valid_ip' => '\projectorangebox\orange\library\validations\Validate_valid_ip',
	'validate_max_length' => '\projectorangebox\orange\library\validations\Validate_max_length',
	'validate_matches' => '\projectorangebox\orange\library\validations\Validate_matches',
	'validate_valid_url' => '\projectorangebox\orange\library\validations\Validate_valid_url',
	'validate_integer' => '\projectorangebox\orange\library\validations\Validate_integer',
	'validate_greater_than_equal_to' => '\projectorangebox\orange\library\validations\Validate_greater_than_equal_to',
	'validate_alpha' => '\projectorangebox\orange\library\validations\Validate_alpha',
	'validate_is_unique' => '\projectorangebox\orange\library\validations\Validate_is_unique',
	'validate_regex_match' => '\projectorangebox\orange\library\validations\Validate_regex_match',
	'validate_valid_base64' => '\projectorangebox\orange\library\validations\Validate_valid_base64',
	'validate_alpha_dash' => '\projectorangebox\orange\library\validations\Validate_alpha_dash',
	'validate_alpha_numeric_spaces' => '\projectorangebox\orange\library\validations\Validate_alpha_numeric_spaces',
	'validate_alpha_numeric' => '\projectorangebox\orange\library\validations\Validate_alpha_numeric',
	'validate_exact_length' => '\projectorangebox\orange\library\validations\Validate_exact_length',
	'validate_alpha_space' => '\projectorangebox\orange\library\validations\Validate_alpha_space',
	'validate_less_than' => '\projectorangebox\orange\library\validations\Validate_less_than',
	'validate_in_list' => '\projectorangebox\orange\library\validations\Validate_in_list',
	'validate_greater_than' => '\projectorangebox\orange\library\validations\Validate_greater_than',
	'validate_is_natural' => '\projectorangebox\orange\library\validations\Validate_is_natural',
	'validate_differs' => '\projectorangebox\orange\library\validations\Validate_differs',
	'validate_valid_email' => '\projectorangebox\orange\library\validations\Validate_valid_email',
	'validate_has_errors' => '\projectorangebox\orange\library\validations\Validate_has_errors',
	'validate_is_natural_no_zero' => '\projectorangebox\orange\library\validations\Validate_is_natural_no_zero',
	'validate_min_length' => '\projectorangebox\orange\library\validations\Validate_min_length',
	'validate_numeric' => '\projectorangebox\orange\library\validations\Validate_numeric',
	'validate_required' => '\projectorangebox\orange\library\validations\Validate_required',
	'validate_less_than_equal_to' => '\projectorangebox\orange\library\validations\Validate_less_than_equal_to',

	'#form/test' => '/packages/projectorangebox/theme/views/form/test.php',

	'#_templates/orange_admin' => '/packages/projectorangebox/theme/views/_templates/orange_admin.php',
	'#_templates/access' => '/packages/projectorangebox/theme/views/_templates/access.php',
	'#_templates/nav' => '/packages/projectorangebox/theme/views/_templates/nav.php',
	'#_templates/footer' => '/packages/projectorangebox/theme/views/_templates/footer.php',
	'#_templates/blank' => '/packages/projectorangebox/theme/views/_templates/blank.php',
	'#_templates/header' => '/packages/projectorangebox/theme/views/_templates/header.php',
	'#_templates/orange_default' => '/packages/projectorangebox/theme/views/_templates/orange_default.php',

	'#cats' => '/packages/projectorangebox/theme/views/cats.php',
	'#form' => '/application/views/form.php',
	'#welcome_message' => '/application/views/welcome_message.php',

	'#errors/html/error_db' => '/application/views/errors/html/error_db.php',
	'#errors/html/error_404' => '/application/views/errors/html/error_404.php',
	'#errors/html/error_php' => '/application/views/errors/html/error_php.php',
	'#errors/html/error_exception' => '/application/views/errors/html/error_exception.php',
	'#errors/html/error_general' => '/application/views/errors/html/error_general.php',
	'#errors/cli/error_db' => '/application/views/errors/cli/error_db.php',
	'#errors/cli/error_404' => '/application/views/errors/cli/error_404.php',
	'#errors/cli/error_php' => '/application/views/errors/cli/error_php.php',
	'#errors/cli/error_exception' => '/application/views/errors/cli/error_exception.php',
	'#errors/cli/error_general' => '/application/views/errors/cli/error_general.php',

	'#welcome/index' => '/application/views/welcome/index.php',
	'#main/index' => '/application/views/welcome/index.php',
];
